### ISSUE TITLE
[ENHANCEMENT] Create Function Get List Video

### ISSUE THREAD

**Issue by setiadijoe** [sapawarga/video-service#1]
## Issue
User can get list video and can filter by regency id

## Task
- [x] create usecase of get list video
- [ ] create endpoint of get list video
- [ ] create transport of get list video
- [x] create repository of get list video
