### ISSUE TITLE
[ENHANCEMENT]  Create Unit Test and Upgrade Coverage

### ISSUE THREAD

**Issue by setiadijoe** [sapawarga/video-service#3]
## Issue
Create unit test for every method in usecase

## Task
- [x] unit test get list video
- [x] unit test get detail video
- [x] unit test update video
- [x] unit test delete video
- [x] unit test create video
- [x] unit test get statistic video

reference with issue #1
