### ISSUE TITLE
[BUGFIX] FIx request and response body using Contract API v1 Sapawarga

### ISSUE THREAD

**Issue by setiadijoe** [sapawarga/video-service#49]
## Issue
Client need request body and response body the same as contract api v1 sapawarga app

## Tasks
- [x] update any request of video service like contract api v1
- [x] update any response of video service like contract api v1

**Comment by setiadijoe** [comment]
- [ ] fix query on update video service
