### ISSUE TITLE
[BUGFIX] Issue on create, get list and update video

### ISSUE THREAD

**Issue by setiadijoe** [sapawarga/video-service#53]
## Issues
- Filter are `kabkota_id`, `title`, and `category_id`
- Error when post video
- Update video can be just one field

## Tasks
- [x] add filter `kabkota_id`, `title` and `category_id`
- [x] add checker when post video for status
- [x] update request body for update
