### ISSUE TITLE
[BUGFIX] Fixed filter parameters for get list video

### ISSUE THREAD

**Issue by setiadijoe** [sapawarga/video-service#61]
## Issue
User get all list of video post

## What should behavior?
User can filter the list with its status and default status is active

## Tasks
- [x] add handler in http to add parameter of status
- [x] set default status to active
- [x] add query for filter with status
